### ISSUE TITLE
Please provide the document in ODF or SVG format

### ISSUE THREAD

**Issue by MagicFab** [pmartinolli/TM-SchoProMa#1]
It would be beneficial to make this document available in an OpenDocument (ODF) or SVG format (using Inkscape) to make it accessible to anyone, not just owners of a MS Publisher 2014 license and Microsoft fonts.

I tried the import function in LibreOffice Draw but for some reason images didn't import and some formatting is missing (see [my bug report at the LO project](https://bugs.documentfoundation.org/show_bug.cgi?id=121800)).

It may be more convenient for now to just install Inkscape and cut + paste the content into it, then save as SVG to make the document freely available and editable.

Thanks for considering this request.

**Comment by pmartinolli** [comment]
Done (in ODF) ! Thanks for your request.

**Comment by MagicFab** [comment]
Nice! Thank you, I noticed the original source in French is not there, perhaps just missed when uploading - just wanted to let you know.

**Comment by pmartinolli** [comment]
Thanks, I just uploaded it.
